[build]
  publish = "public"

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 200

[[redirects]]
  from = "/reservation"
  to = "/reservation.html"
  status = 200

[[redirects]]
  from = "/a-propos"
  to = "/a-propos.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
